apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: thoms@mypatch.fr
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - dns01: {} # Remove the "ingress" field

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate
spec:
  secretName: wildcard-certificate-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.mypatch.fr"
  dnsNames:
    - "*.mypatch.fr"
